#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::home

fomrmulaire:
  path: /formulaire-de-contact
  controller: App\Controller\FormController::formulaire

adaptation_cinema:
  path: /adaptation-cinema
  controller: App\Controller\HomeController::adaptationCinema

bande_dessinee:
  path: /bande-dessinee
  controller: App\Controller\HomeController::bandeDessinee

cinema:
  path: /cinema
  controller: App\Controller\HomeController::cinema

ecrits:
  path: /ecrits
  controller: App\Controller\HomeController::ecrits

enseignements:
  path: /enseignements
  controller: App\Controller\HomeController::enseignements

livres_objets:
  path: /livres-objets
  controller: App\Controller\HomeController::livresObjets

mise_en_scene:
  path: /mise-en-scene
  controller: App\Controller\HomeController::miseEnScene

peinture:
  path: /peinture
  controller: App\Controller\HomeController::peinture

sculptures:
  path: /sculptures
  controller: App\Controller\HomeController::sculptures

theatre:
  path: /theatre
  controller: App\Controller\HomeController::theatre



admin_home:
  path: /admin-home
  controller: App\Controller\AdminController::adminHome

admin_adaptation_cinema:
  path: /admin/adaptation-cinema
  controller: App\Controller\AdminController::adminAdaptationCinema

admin_bande_dessinee:
  path: /admin/bande-dessinee
  controller: App\Controller\AdminController::adminBandeDessinee

admin_cinema:
  path: /admin/cinema
  controller: App\Controller\AdminController::adminCinema

admin_ecrits:
  path: /admin/ecrits
  controller: App\Controller\AdminController::adminEcrits

admin_enseignements:
  path: /admin/enseignements
  controller: App\Controller\AdminController::adminEnseignement

admin_livres_objets:
  path: /admin/livres-objets
  controller: App\Controller\AdminController::adminLivresObjets

admin_mise_en_scene:
  path: /admin/mise-en-scene
  controller: App\Controller\AdminController::adminMiseEnScene

admin_peinture:
  path: /admin/peinture
  controller: App\Controller\AdminController::adminPeinture

admin_sculptures:
  path: /admin/sculptures
  controller: App\Controller\AdminController::adminSculptures

admin_theatre:
  path: /admin/theatre
  controller: App\Controller\AdminController::adminTheatre




update_article:
  path: /admin/article/update
  controller: App\Controller\AdminController::updateArticle


delete_article:
  path: /admin/article/delete/{idArticle}
  controller: App\Controller\AdminController::deleteArticle


create_article:
  path: /admin/article/create
  controller: App\Controller\AdminController::createArticle


create_category:
  path: /admin/category/create
  controller: App\Controller\AdminController::createCategory

