#index:
#    path: /
#    controller: App\Controller\DefaultController::index


login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  
home:
  path: /
  controller: App\Controller\HomeController::home



dashboard:
  path: /dashboard
  controller: App\Controller\AdminController::dashboardAction


update_article:
  path: /dashboard/modifier/{id}
  controller: App\Controller\AdminController::updateArticle


delete_article:
  path: /dashboard/delete/{idArticle}
  controller: App\Controller\AdminController::deleteArticle


create_article:
  path: /dashboard/create_article
  controller: App\Controller\AdminController::createArticle

sidebar:
  path: /sidebar
  controller: App\Controller\SidebarController::home
  
category:
  path: /category/{name}
  controller: App\Controller\CategoryController::categoryAction




