#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::home

fomrmulaire:
  path: /formulaire-de-contact
  controller: App\Controller\FormController::formulaire

adaptation_cinema:
  path: /adaptation-cinema
  controller: App\Controller\HomeController::adaptationCinema

bande_dessinee:
  path: /bande-dessinee
  controller: App\Controller\HomeController:bandeDessinee

cinema:
  path: /cinema
  controller: App\Controller\HomeController:cinema

ecrits:
  path: /ecrits
  controller: App\Controller\HomeController:ecrits

enseignements:
  path: /enseignements
  controller: App\Controller\HomeController:enseignements

livres_objets:
  path: /livres-objets
  controller: App\Controller\HomeController:livresObjets

mise_en_scene:
  path: /mise-en-scene
  controller: App\Controller\HomeController:miseEnScene

peinture:
  path: /peinture
  controller: App\Controller\HomeController:peinture

sculptures:
  path: /sculptures
  controller: App\Controller\HomeController:sculptures

theatre:
  path: /theatre
  controller: App\Controller\HomeController:theatre



admin_home:
  path: /admin-home
  controller: App\Controller\AdminController:adminHome

admin_adaptation_cinema:
  path: /admin/adaptation-cinema
  controller: App\Controller\AdminController::adminCinema

admin_bande_dessinee:
  path: /admin/bande-dessinee
  controller: App\Controller\AdminController:adminBandeDessinee

admin_cinema:
  path: /admin/cinema
  controller: App\Controller\AdminController:adminCinema

admin_ecrits:
  path: /admin/ecrits
  controller: App\Controller\AdminController:adminEcrits

admin_enseignements:
  path: /admin/enseignements
  controller: App\Controller\AdminController:adminEnseignements

admin_livres_objets:
  path: /admin/livres-objets
  controller: App\Controller\AdminController:adminLivresObjets

admin_mise_en_scene:
  path: /admin/mise-en-scene
  controller: App\Controller\AdminController:adminMiseEnScene

admin_peinture:
  path: /admin/peinture
  controller: App\Controller\AdminController:adminPeinture

admin_sculptures:
  path: /admin/sculptures
  controller: App\Controller\AdminController:adminSculptures

admin_theatre:
  path: /admin/theatre
  controller: App\Controller\AdminController:adminTheatre



admin_update_adaptation_cinema:
  path: /admin/adaptation-cinema/update
  controller: App\Controller\AdminController::updateCinema

admin_update_bande_dessinee:
  path: /admin/bande-dessinee/update
  controller: App\Controller\AdminController:updateBandeDessinee

admin_update_cinema:
  path: /admin/cinema/update
  controller: App\Controller\AdminController:updateCinema

admin_update_ecrits:
  path: /admin/ecrits/update
  controller: App\Controller\AdminController:updateEcrits

admin_update_enseignements:
  path: /admin/enseignements/update
  controller: App\Controller\AdminController:updateEnseignements

admin_update_livres_objets:
  path: /admin/livres-objets/update
  controller: App\Controller\AdminController:updateLivresObjets

admin_upadate_mise_en_scene:
  path: /admin/mise-en-scene/update
  controller: App\Controller\AdminController:updateMiseEnScene

admin_update_peinture:
  path: /admin/peinture/update
  controller: App\Controller\AdminController:updatePeinture

admin_update_sculptures:
  path: /admin/sculptures/update
  controller: App\Controller\AdminController:updateSculptures

admin_update_theatre:
  path: /admin/theatre/update
  controller: App\Controller\AdminController:updateTheatre



admin_delete_adaptation_cinema:
  path: /admin/adaptation-cinema/delete
  controller: App\Controller\AdminController::deleteCinema

admin_delete_bande_dessinee:
  path: /admin/bande-dessinee/delete
  controller: App\Controller\AdminController:deleteBandeDessinee

admin_delete_cinema:
  path: /admin/cinema/delete
  controller: App\Controller\AdminController:deleteCinema

admin_delete_ecrits:
  path: /admin/ecrits/update
  controller: App\Controller\AdminController:deleteEcrits

admin_delete_enseignements:
  path: /admin/enseignements/delete
  controller: App\Controller\AdminController:deleteEnseignements

admin_delete_livres_objets:
  path: /admin/livres-objets/delete
  controller: App\Controller\AdminController:deleteLivresObjets

admin_delete_mise_en_scene:
  path: /admin/mise-en-scene/delete
  controller: App\Controller\AdminController:deleteMiseEnScene

admin_delete_peinture:
  path: /admin/peinture/delete
  controller: App\Controller\AdminController:deletePeinture

admin_delete_sculptures:
  path: /admin/sculptures/delete
  controller: App\Controller\AdminController:deleteSculptures

admin_delete_theatre:
  path: /admin/theatre/delete
  controller: App\Controller\AdminController:deleteTheatre
